# C/C++: 1. Intel Tremont 2. Omit frame pointer 3. O2 optimization (ideal for Atom core pipelines)
CFLAGS="-march=tremont -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fomit-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"

export RUSTFLAGS="-C target-cpu=tremont"

export GOAMD64="v2"

MAKEFLAGS="-j$(nproc)"
