# C/C++: 1. Intel Alderlake (12th-Gen hybrid) 2. Omit frame pointer 3. O3 optimization
CFLAGS="-march=alderlake -O3 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fomit-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"

# Rust: Optimize for Alderlake microarchitecture and force Thin LTO
export RUSTFLAGS="-C target-cpu=alderlake -C opt-level=3 -C lto=thin"

# Go: Optimize for AMD64 v3 microarchitecture level (AVX2, NO AVX-512)
export GOAMD64="v3"

MAKEFLAGS="-j$(nproc)"
