# C/C++: 1. Intel Alderlake (12th-Gen hybrid) 2. Omit frame pointer 3. O3 optimization
CFLAGS="-march=alderlake -O3 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fomit-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"

export RUSTFLAGS="-C target-cpu=alderlake"

export GOAMD64="v3"

MAKEFLAGS="-j$(nproc)"
