# C/C++: 1. AMD Zen 5 (znver5) 2. Omit frame pointer 3. O3 optimization
CFLAGS="-march=znver5 -O3 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fomit-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"

export RUSTFLAGS="-C target-cpu=znver5"

export GOAMD64="v4"

MAKEFLAGS="-j$(nproc)"
