# If a package in this profile attempts to compile native code,
# the compiler will encounter an invalid flag and crash immediately.
# This guarantees that only march-agnostic packages can be built.

CFLAGS="-march=invalid-generic-cpu-compilation-forbidden-error"
CXXFLAGS="$CFLAGS"

export RUSTFLAGS="-C target-cpu=invalid-generic-rust-compilation-forbidden-error"

export GOAMD64="invalid_generic_go_compilation_forbidden_error"

MAKEFLAGS="-j$(nproc)"
